// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppQr: typeof import('./src/components/home/AppQr.vue')['default']
    BaseInfo: typeof import('./src/components/stock/BaseInfo.vue')['default']
    BookInfo: typeof import('./src/components/detail/BookInfo.vue')['default']
    CatalogList: typeof import('./src/components/detail/CatalogList.vue')['default']
    CategoryBook: typeof import('./src/components/category/CategoryBook.vue')['default']
    CategoryItem: typeof import('./src/components/category/CategoryItem.vue')['default']
    CloseLine: typeof import('./src/components/stock/chart/CloseLine.vue')['default']
    Comment: typeof import('./src/components/detail/Comment.vue')['default']
    ContentHeader: typeof import('./src/components/content/ContentHeader.vue')['default']
    ContentTxt: typeof import('./src/components/content/ContentTxt.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    Header: typeof import('./src/components/home/Header.vue')['default']
    HomeBook: typeof import('./src/components/home/HomeBook.vue')['default']
    Left: typeof import('./src/components/stock/Left.vue')['default']
    Like: typeof import('./src/components/home/Like.vue')['default']
    Line: typeof import('./src/components/stock/Line.vue')['default']
    LoginQr: typeof import('./src/components/home/LoginQr.vue')['default']
    Menu: typeof import('./src/components/home/Menu.vue')['default']
    MyShelf: typeof import('./src/components/home/MyShelf.vue')['default']
    PriceLine: typeof import('./src/components/stock/PriceLine.vue')['default']
    Recommend: typeof import('./src/components/detail/Recommend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/Search.vue')['default']
    TableList: typeof import('./src/components/stock/table/TableList.vue')['default']
    TopHeader: typeof import('./src/components/home/TopHeader.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
